services:
    mongohost:              
        image: mongo:bionic      
        restart: always    
        container_name: parcelmongodb
        volumes:
         - dbdata:/data/db
        ports:
        - 27017:27017
      
    web:
        build: .        
        restart: always
        container_name: parcelwebapi
        ports:
          - 5000:8080 
        depends_on:     
          - mongohost
volumes:                
  dbdata:    
